version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432 ## 左側が自分のコンピュータのport 右側がdockerコンテナ内のpostgresのport
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always
    networks:
      - lesson
networks:
  lesson: